### ISSUE TITLE
Try to use ECKey as interface for bign keys

### ISSUE THREAD

**Issue by pavlovkv** [bcrypto/bee2j#10]
Use ECKey (https://docs.oracle.com/javase/8/docs/api/java/security/interfaces/ECKey.html) in bign keys hierarchy

**Comment by blackbearman** [comment]
Interface ECKey add only one method:
[ECParameterSpec](https://docs.oracle.com/javase/8/docs/api/java/security/spec/ECParameterSpec.html) getParams().
Classes to be supported:
1. [ECParameterSpec](https://docs.oracle.com/javase/8/docs/api/java/security/spec/ECParameterSpec.html) 
2. [EllipticCurve](https://docs.oracle.com/javase/8/docs/api/java/security/spec/EllipticCurve.html)
3. [ECPoint](https://docs.oracle.com/javase/8/docs/api/java/security/spec/ECPoint.html)
4. [BigInteger](https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html)
5. [ECField](https://docs.oracle.com/javase/8/docs/api/java/security/spec/ECField.html)

**Comment by blackbearman** [comment]
public BignParams getParams() is supported in BignKey. It seems to be more usable  than ECParameterSpec.
